### ISSUE TITLE
Influence of reference character and component coverage on results

### ISSUE THREAD

**Issue by moonfoam** [tlc121/FsFont#12]
Thanks for open-sourcing this inspiring work!

I am now doing some comparative experiments for this work. The visualization of the training process seems to work fine. However, the output of the test is not so good. I guess the reason may be that the components of reference characters do not cover the test set well. (since the number of all our reference characters is 16)

So I wonder if the choice of reference characters and the coverage of the components have a big impact on the results?

**Comment by tlc121** [comment]
> 

Yes, the content-reference mapping is significant in experiments. Could u give some examples of your cr_mapping dict?

**Comment by tlc121** [comment]
> Thanks for open-sourcing this inspiring work!
> 
> I am now doing some comparative experiments for this work. The visualization of the training process seems to work fine. However, the output of the test is not so good. I guess the reason may be that the components of reference characters do not cover the test set well. (since the number of all our reference characters is 16)
> 
> So I wonder if the choice of reference characters and the coverage of the components have a big impact on the results?


Yes, the content-reference mapping is significant in experiments. Could u give some examples of your cr_mapping dict?

**Comment by moonfoam** [comment]
Thanks for your quick reply.

We discovered this while doing one-shot and few-shot comparison (around fifteen characters in total) experiments . But since the reference character set is randomly selected and fixed, many components are actually not covered, which may be unfair to this method. By the way, the component-wise spatial correspondence in this paper is well designed and inspired me a lot.

**Comment by tlc121** [comment]
> Thanks for your quick reply.
> 
> We discovered this while doing one-shot and few-shot comparison (around fifteen characters in total) experiments . But since the reference character set is randomly selected and fixed, many components are actually not covered, which may be unfair to this method. By the way, the component-wise spatial correspondence in this paper is well designed and inspired me a lot.

Thats right, Fsfont highly depends on the reference selection and was designed in component-wise, so one-shot task is not suitable for it.  Actually there are already some works introducing stroke-wise attention in font generation. Hope it could help you : )

**Comment by moonfoam** [comment]
> > Thanks for your quick reply.
> > We discovered this while doing one-shot and few-shot comparison (around fifteen characters in total) experiments . But since the reference character set is randomly selected and fixed, many components are actually not covered, which may be unfair to this method. By the way, the component-wise spatial correspondence in this paper is well designed and inspired me a lot.
> 
> Thats right, Fsfont highly depends on the reference selection and was designed in component-wise, so one-shot task is not suitable for it. Actually there are already some works introducing stroke-wise attention in FFG. Hope it could help you : )

Thank you @tlc121 for the reply.

**Comment by zi1zi** [comment]
> > 感谢您的快速回复。
> > 我们在做一次和少量比较（总共大约十五个字符）实验时发现了这一点。但是由于参考字符集是随机选择和固定的，所以很多组件实际上并没有被覆盖，这可能对这种方法不公平。顺便说一句，本文中的组件空间对应关系设计得很好，给了我很大的启发。
> 
> 没错，Fsfont 高度依赖于参考选择，并且是按组件设计的，因此一次性任务不适合它。实际上已经有一些作品在 FFG 中引入了 stroke-wise attention。希望它能帮助你:)

您好，请问您能列举一些stroke-wise attention的相关文献吗？

**Comment by tlc121** [comment]
> > > 感谢您的快速回复。
> > > 我们在做一次和少量比较（总共大约十五个字符）实验时发现了这一点。但是由于参考字符集是随机选择和固定的，所以很多组件实际上并没有被覆盖，这可能对这种方法不公平。顺便说一句，本文中的组件空间对应关系设计得很好，给了我很大的启发。
> > 
> > 
> > 没错，Fsfont 高度依赖于参考选择，并且是按组件设计的，因此一次性任务不适合它。实际上已经有一些作品在 FFG 中引入了 stroke-wise attention。希望它能帮助你:)
> 
> 您好，请问您能列举一些stroke-wise attention的相关文献吗？
字节的xmpfont就是stroke-wise的，还有一篇华为的文章，具体名字忘了，您可以自行搜索下。

**Comment by tlc121** [comment]
> > > 感谢您的快速回复。
> > > 我们在做一次和少量比较（总共大约十五个字符）实验时发现了这一点。但是由于参考字符集是随机选择和固定的，所以很多组件实际上并没有被覆盖，这可能对这种方法不公平。顺便说一句，本文中的组件空间对应关系设计得很好，给了我很大的启发。
> > 
> > 
> > 没错，Fsfont 高度依赖于参考选择，并且是按组件设计的，因此一次性任务不适合它。实际上已经有一些作品在 FFG 中引入了 stroke-wise attention。希望它能帮助你:)
> 
> 您好，请问您能列举一些stroke-wise attention的相关文献吗？

字节的xmpfont就是stroke-wise的，还有一篇华为的文章，具体名字有点忘了，您可以自行搜索下
