### ISSUE TITLE
训练过程中评估的问题

### ISSUE THREAD

**Issue by zhenzi0322** [tlc121/FsFont#25]
![image](https://github.com/tlc121/FsFont/assets/34839719/45952396-d116-49f5-8532-db2bf38841e3)

为什么会出现这种情况的呢？是因为我准备映射文件问题嘛，我目前使用的项目中自带的映射文件`cr_mapping.json`。

**Comment by tlc121** [comment]
这是测试集吗？很明显能看出你的reference字和推理字部首不匹配啊

**Comment by zhenzi0322** [comment]
我也很奇怪，我准备的映射文件中是没有诊和张这些字的。差不多都是我没有准备的那些字是有问题的

**Comment by zhenzi0322** [comment]
> 这是测试集吗？很明显能看出你的reference字和推理字部首不匹配啊

是测试集。训练过程中生成的图像。

**Comment by tlc121** [comment]
datasets/dataset_transformer.py 这个文件的的line154，因为你的cr_mapping只有几个字。所以进入random.sample的逻辑了

> > 这是测试集吗？很明显能看出你的reference字和推理字部首不匹配啊
> 
> 是测试集。训练过程中生成的图像。

**Comment by zhenzi0322** [comment]
这样呀，那我最少需要准备多少个cr_mapping的汉字才会使用我自己的映射文件json。

**Comment by tlc121** [comment]
只要cr_mapping的key能覆盖val_unis.json里的汉字就能跑呀。

**Comment by zhenzi0322** [comment]
`val_unis.json`里面的列表中的数据就是对应的`cr_mapping.json`中的所有`key`？

**Comment by zhenzi0322** [comment]
我前面训练采用的是`val_unis.json`中的数据对应的是`cr_mapping.json`中的所有字符包含`key`和`value`。如果有重复的话就保留一个。估计是我种方式训练错误了。

**Comment by tlc121** [comment]
> `val_unis.json`里面的列表中的数据就是对应的`cr_mapping.json`中的所有`key`？

val_unis、train_unis这两个列表 包含于 cr_mapping。这两个unis列表的数量理应都比cr_mapping的key少
