### ISSUE TITLE
请教一下，使用本项目如何训练字母和数字？

### ISSUE THREAD

**Issue by zhenzi0322** [tlc121/FsFont#26]

**Comment by zhenzi0322** [comment]
针对于字母和数字如何准备映射文件`cr_mapping`

**Comment by tlc121** [comment]
字母和数字就随机匹配吧

**Comment by zhenzi0322** [comment]
如何随机匹配呢，映射文件不需要编写嘛？

**Comment by tlc121** [comment]
> 如何随机匹配呢，映射文件不需要编写嘛？

需要映射文件，但是文件内容中的mapping可以随机匹配，不需要像中文一样保证偏旁的对应

**Comment by zhenzi0322** [comment]
好的，是类似如下的随机匹配不：

```json
{"a": ["V", "T", "6"], "b": ["U", "N", "E"], "c": ["d", "r", "c"], "d": ["P", "t", "2"], "e": ["x", "d", "9"]}
```

**Comment by tlc121** [comment]
> 好的，是类似如下的随机匹配不：
> 
> ```json
> {"a": ["V", "T", "6"], "b": ["U", "N", "E"], "c": ["d", "r", "c"], "d": ["P", "t", "2"], "e": ["x", "d", "9"]}
> ```

可以的

**Comment by zhenzi0322** [comment]
那标点符号那些也是随机匹配即可？
