### ISSUE TITLE
Content-Reference mapping

### ISSUE THREAD

**Issue by Stareven233** [tlc121/FsFont#5]
您好，我看过了对应的论文以及部分代码，觉得这是非常精彩的一项工作，但是注意到关键的 meta/cr_mapping.json 文件似乎并没有完整放出。如果方便的话能否分享一下这个文件，保证仅用于学术研究。  

或者可否指点一下如何生成它？以下是我对论文中 Reference Selection 小节的一些疑问    
1. 根据论文reference一共选取100个，每个汉字有3个对应的参考，关于reference的选取 "Once the character contains two or more new components, we add this character to our reference set."是不是说部件越多越复杂的汉字更应作为reference呢？像 "夒、𩱀、𩱪"
2.  "一、乙" 这种独体字不必作为reference，因为可以由其他包含它们的reference（如大、艺）生成，对吗？
3.  论文中提及的ids.txt里，部分行包含了一些其他符号，如 "U+4E0E   与   ⿹②一[GTKV]    ⿻②一[J]"，这里的②似乎代替了无法表示的一个部件，但很显然这种表示会跟其他同笔画数的部件重复，请问这种情况该如何处理呢？

非常感谢您耐心地看到这里，期待得到您的回复，衷心祝您身体健康工作顺利

**Comment by Yaomingshuai** [comment]
请问这个cr-mapping您有好的解决方案吗？

**Comment by Stareven233** [comment]
没办法，目前打算先试着解析那个ids.txt，实在不行就算了，总不能手动标注把...

**Comment by Stareven233** [comment]
> 请问这个cr-mapping您有好的解决方案吗？

没办法，目前打算先试着解析那个ids.txt，实在不行就算了，总不能手动标注把...

**Comment by Yaomingshuai** [comment]
想请问一下现在这个cr_mapping进行的怎么样了？看起来不是很容易生成

**Comment by Stareven233** [comment]
对我而言不太容易，ids里面的带圈数字不会处理，字分解到什么程度合适也无法统一，论文中 374个 conspicuos components 也找不到，
参考字偏简单或复杂都不合适，更别提ids.txt里一堆错误，最终怎么也无法用100个参考字覆盖那些components。
已经准备看别的论文了

**Comment by Yaomingshuai** [comment]
好的，我打算尝试几天看看可不可以解决这个问题，感觉这篇文章做的还是不错的。

**Comment by awei669** [comment]
请问你们cr_mapping进行到哪一步了？

**Comment by ChenSiyi1** [comment]
> 请问你们cr_mapping进行到哪一步了？

打扰了，请问有CR-mapping的数据集可以分享一下吗？非常感谢。

**Comment by Yaomingshuai** [comment]
我们利用ids.txt文件制作了一份。这个只要把规则写清楚就行。我记得用到了树的遍历



发自我的iPhone


------------------ Original ------------------
From: ChenSiyi ***@***.***&gt;
Date: Mon,Dec 11,2023 9:34 PM
To: tlc121/FsFont ***@***.***&gt;
Cc: msYao ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [tlc121/FsFont] Content-Reference mapping (Issue #5)





  
请问你们cr_mapping进行到哪一步了？
  
打扰了，请问有CR-mapping的数据集可以分享一下吗？非常感谢。

**Comment by Yaomingshuai** [comment]
我们利用ids.txt按照Fsfont中的代码制作了一份。



发自我的iPhone


------------------ Original ------------------
From: ChenSiyi ***@***.***&gt;
Date: Mon,Dec 11,2023 9:34 PM
To: tlc121/FsFont ***@***.***&gt;
Cc: msYao ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [tlc121/FsFont] Content-Reference mapping (Issue #5)





  
请问你们cr_mapping进行到哪一步了？
  
打扰了，请问有CR-mapping的数据集可以分享一下吗？非常感谢。

**Comment by positive-man** [comment]
> 我们利用ids.txt按照Fsfont中的代码制作了一份。 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: ChenSiyi ***@***.***&gt; Date: Mon,Dec 11,2023 9:34 PM To: tlc121/FsFont ***@***.***&gt; Cc: msYao ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [tlc121/FsFont] Content-Reference mapping (Issue #5) 请问你们cr_mapping进行到哪一步了？ 打扰了，请问有CR-mapping的数据集可以分享一下吗？非常感谢。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

您好，能分享一下你们制作的CR-mapping吗？非常感谢。
